/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillasRouteImport } from './routes/villas'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListVillaRouteImport } from './routes/list-villa'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BecomeOrganizerRouteImport } from './routes/become-organizer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillasIdRouteImport } from './routes/villas.$id'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as OrganizerIdRouteImport } from './routes/organizer.$id'
import { Route as HostIdRouteImport } from './routes/host.$id'
import { Route as ExperiencesIdRouteImport } from './routes/experiences.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DashboardVillaOwnerRouteImport } from './routes/dashboard.villa-owner'
import { Route as DashboardOrganizerRouteImport } from './routes/dashboard.organizer'
import { Route as CheckoutEventRouteImport } from './routes/checkout.event'
import { Route as BookingVillaRouteImport } from './routes/booking.villa'
import { Route as AdminVillasRouteImport } from './routes/admin.villas'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as DashboardVillaOwnerSettingsRouteImport } from './routes/dashboard.villa-owner.settings'
import { Route as DashboardVillaOwnerPropertiesRouteImport } from './routes/dashboard.villa-owner.properties'
import { Route as DashboardVillaOwnerEarningsRouteImport } from './routes/dashboard.villa-owner.earnings'
import { Route as DashboardVillaOwnerBookingsRouteImport } from './routes/dashboard.villa-owner.bookings'
import { Route as DashboardOrganizerTicketsRouteImport } from './routes/dashboard.organizer.tickets'
import { Route as DashboardOrganizerSettingsRouteImport } from './routes/dashboard.organizer.settings'
import { Route as DashboardOrganizerEventsRouteImport } from './routes/dashboard.organizer.events'
import { Route as DashboardOrganizerAttendeesRouteImport } from './routes/dashboard.organizer.attendees'
import { Route as DashboardOrganizerAnalyticsRouteImport } from './routes/dashboard.organizer.analytics'
import { Route as CheckoutEventSuccessRouteImport } from './routes/checkout.event.success'
import { Route as BookingVillaSuccessRouteImport } from './routes/booking.villa.success'
import { Route as DashboardOrganizerEventsNewRouteImport } from './routes/dashboard.organizer.events.new'

const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListVillaRoute = ListVillaRouteImport.update({
  id: '/list-villa',
  path: '/list-villa',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeOrganizerRoute = BecomeOrganizerRouteImport.update({
  id: '/become-organizer',
  path: '/become-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasIdRoute = VillasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VillasRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIdRoute = OrganizerIdRouteImport.update({
  id: '/organizer/$id',
  path: '/organizer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIdRoute = HostIdRouteImport.update({
  id: '/host/$id',
  path: '/host/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIdRoute = ExperiencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExperiencesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardVillaOwnerRoute = DashboardVillaOwnerRouteImport.update({
  id: '/dashboard/villa-owner',
  path: '/dashboard/villa-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizerRoute = DashboardOrganizerRouteImport.update({
  id: '/dashboard/organizer',
  path: '/dashboard/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutEventRoute = CheckoutEventRouteImport.update({
  id: '/checkout/event',
  path: '/checkout/event',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingVillaRoute = BookingVillaRouteImport.update({
  id: '/booking/villa',
  path: '/booking/villa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVillasRoute = AdminVillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardVillaOwnerSettingsRoute =
  DashboardVillaOwnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardVillaOwnerRoute,
  } as any)
const DashboardVillaOwnerPropertiesRoute =
  DashboardVillaOwnerPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => DashboardVillaOwnerRoute,
  } as any)
const DashboardVillaOwnerEarningsRoute =
  DashboardVillaOwnerEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => DashboardVillaOwnerRoute,
  } as any)
const DashboardVillaOwnerBookingsRoute =
  DashboardVillaOwnerBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => DashboardVillaOwnerRoute,
  } as any)
const DashboardOrganizerTicketsRoute =
  DashboardOrganizerTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardOrganizerRoute,
  } as any)
const DashboardOrganizerSettingsRoute =
  DashboardOrganizerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardOrganizerRoute,
  } as any)
const DashboardOrganizerEventsRoute =
  DashboardOrganizerEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardOrganizerRoute,
  } as any)
const DashboardOrganizerAttendeesRoute =
  DashboardOrganizerAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => DashboardOrganizerRoute,
  } as any)
const DashboardOrganizerAnalyticsRoute =
  DashboardOrganizerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardOrganizerRoute,
  } as any)
const CheckoutEventSuccessRoute = CheckoutEventSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutEventRoute,
} as any)
const BookingVillaSuccessRoute = BookingVillaSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookingVillaRoute,
} as any)
const DashboardOrganizerEventsNewRoute =
  DashboardOrganizerEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardOrganizerEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/list-villa': typeof ListVillaRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/villas': typeof VillasRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/villas': typeof AdminVillasRoute
  '/booking/villa': typeof BookingVillaRouteWithChildren
  '/checkout/event': typeof CheckoutEventRouteWithChildren
  '/dashboard/organizer': typeof DashboardOrganizerRouteWithChildren
  '/dashboard/villa-owner': typeof DashboardVillaOwnerRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/host/$id': typeof HostIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/villas/$id': typeof VillasIdRoute
  '/booking/villa/success': typeof BookingVillaSuccessRoute
  '/checkout/event/success': typeof CheckoutEventSuccessRoute
  '/dashboard/organizer/analytics': typeof DashboardOrganizerAnalyticsRoute
  '/dashboard/organizer/attendees': typeof DashboardOrganizerAttendeesRoute
  '/dashboard/organizer/events': typeof DashboardOrganizerEventsRouteWithChildren
  '/dashboard/organizer/settings': typeof DashboardOrganizerSettingsRoute
  '/dashboard/organizer/tickets': typeof DashboardOrganizerTicketsRoute
  '/dashboard/villa-owner/bookings': typeof DashboardVillaOwnerBookingsRoute
  '/dashboard/villa-owner/earnings': typeof DashboardVillaOwnerEarningsRoute
  '/dashboard/villa-owner/properties': typeof DashboardVillaOwnerPropertiesRoute
  '/dashboard/villa-owner/settings': typeof DashboardVillaOwnerSettingsRoute
  '/dashboard/organizer/events/new': typeof DashboardOrganizerEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/list-villa': typeof ListVillaRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/villas': typeof VillasRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/villas': typeof AdminVillasRoute
  '/booking/villa': typeof BookingVillaRouteWithChildren
  '/checkout/event': typeof CheckoutEventRouteWithChildren
  '/dashboard/organizer': typeof DashboardOrganizerRouteWithChildren
  '/dashboard/villa-owner': typeof DashboardVillaOwnerRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/host/$id': typeof HostIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/villas/$id': typeof VillasIdRoute
  '/booking/villa/success': typeof BookingVillaSuccessRoute
  '/checkout/event/success': typeof CheckoutEventSuccessRoute
  '/dashboard/organizer/analytics': typeof DashboardOrganizerAnalyticsRoute
  '/dashboard/organizer/attendees': typeof DashboardOrganizerAttendeesRoute
  '/dashboard/organizer/events': typeof DashboardOrganizerEventsRouteWithChildren
  '/dashboard/organizer/settings': typeof DashboardOrganizerSettingsRoute
  '/dashboard/organizer/tickets': typeof DashboardOrganizerTicketsRoute
  '/dashboard/villa-owner/bookings': typeof DashboardVillaOwnerBookingsRoute
  '/dashboard/villa-owner/earnings': typeof DashboardVillaOwnerEarningsRoute
  '/dashboard/villa-owner/properties': typeof DashboardVillaOwnerPropertiesRoute
  '/dashboard/villa-owner/settings': typeof DashboardVillaOwnerSettingsRoute
  '/dashboard/organizer/events/new': typeof DashboardOrganizerEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/list-villa': typeof ListVillaRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/villas': typeof VillasRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/villas': typeof AdminVillasRoute
  '/booking/villa': typeof BookingVillaRouteWithChildren
  '/checkout/event': typeof CheckoutEventRouteWithChildren
  '/dashboard/organizer': typeof DashboardOrganizerRouteWithChildren
  '/dashboard/villa-owner': typeof DashboardVillaOwnerRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/host/$id': typeof HostIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/villas/$id': typeof VillasIdRoute
  '/booking/villa/success': typeof BookingVillaSuccessRoute
  '/checkout/event/success': typeof CheckoutEventSuccessRoute
  '/dashboard/organizer/analytics': typeof DashboardOrganizerAnalyticsRoute
  '/dashboard/organizer/attendees': typeof DashboardOrganizerAttendeesRoute
  '/dashboard/organizer/events': typeof DashboardOrganizerEventsRouteWithChildren
  '/dashboard/organizer/settings': typeof DashboardOrganizerSettingsRoute
  '/dashboard/organizer/tickets': typeof DashboardOrganizerTicketsRoute
  '/dashboard/villa-owner/bookings': typeof DashboardVillaOwnerBookingsRoute
  '/dashboard/villa-owner/earnings': typeof DashboardVillaOwnerEarningsRoute
  '/dashboard/villa-owner/properties': typeof DashboardVillaOwnerPropertiesRoute
  '/dashboard/villa-owner/settings': typeof DashboardVillaOwnerSettingsRoute
  '/dashboard/organizer/events/new': typeof DashboardOrganizerEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/bookings'
    | '/contact'
    | '/events'
    | '/experiences'
    | '/feed'
    | '/help'
    | '/list-villa'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/organizers'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/tickets'
    | '/villas'
    | '/admin/approvals'
    | '/admin/events'
    | '/admin/users'
    | '/admin/villas'
    | '/booking/villa'
    | '/checkout/event'
    | '/dashboard/organizer'
    | '/dashboard/villa-owner'
    | '/events/$id'
    | '/experiences/$id'
    | '/host/$id'
    | '/organizer/$id'
    | '/profile/$username'
    | '/tickets/$id'
    | '/villas/$id'
    | '/booking/villa/success'
    | '/checkout/event/success'
    | '/dashboard/organizer/analytics'
    | '/dashboard/organizer/attendees'
    | '/dashboard/organizer/events'
    | '/dashboard/organizer/settings'
    | '/dashboard/organizer/tickets'
    | '/dashboard/villa-owner/bookings'
    | '/dashboard/villa-owner/earnings'
    | '/dashboard/villa-owner/properties'
    | '/dashboard/villa-owner/settings'
    | '/dashboard/organizer/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/bookings'
    | '/contact'
    | '/events'
    | '/experiences'
    | '/feed'
    | '/help'
    | '/list-villa'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/organizers'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/tickets'
    | '/villas'
    | '/admin/approvals'
    | '/admin/events'
    | '/admin/users'
    | '/admin/villas'
    | '/booking/villa'
    | '/checkout/event'
    | '/dashboard/organizer'
    | '/dashboard/villa-owner'
    | '/events/$id'
    | '/experiences/$id'
    | '/host/$id'
    | '/organizer/$id'
    | '/profile/$username'
    | '/tickets/$id'
    | '/villas/$id'
    | '/booking/villa/success'
    | '/checkout/event/success'
    | '/dashboard/organizer/analytics'
    | '/dashboard/organizer/attendees'
    | '/dashboard/organizer/events'
    | '/dashboard/organizer/settings'
    | '/dashboard/organizer/tickets'
    | '/dashboard/villa-owner/bookings'
    | '/dashboard/villa-owner/earnings'
    | '/dashboard/villa-owner/properties'
    | '/dashboard/villa-owner/settings'
    | '/dashboard/organizer/events/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/bookings'
    | '/contact'
    | '/events'
    | '/experiences'
    | '/feed'
    | '/help'
    | '/list-villa'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/organizers'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/tickets'
    | '/villas'
    | '/admin/approvals'
    | '/admin/events'
    | '/admin/users'
    | '/admin/villas'
    | '/booking/villa'
    | '/checkout/event'
    | '/dashboard/organizer'
    | '/dashboard/villa-owner'
    | '/events/$id'
    | '/experiences/$id'
    | '/host/$id'
    | '/organizer/$id'
    | '/profile/$username'
    | '/tickets/$id'
    | '/villas/$id'
    | '/booking/villa/success'
    | '/checkout/event/success'
    | '/dashboard/organizer/analytics'
    | '/dashboard/organizer/attendees'
    | '/dashboard/organizer/events'
    | '/dashboard/organizer/settings'
    | '/dashboard/organizer/tickets'
    | '/dashboard/villa-owner/bookings'
    | '/dashboard/villa-owner/earnings'
    | '/dashboard/villa-owner/properties'
    | '/dashboard/villa-owner/settings'
    | '/dashboard/organizer/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeOrganizerRoute: typeof BecomeOrganizerRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  FeedRoute: typeof FeedRoute
  HelpRoute: typeof HelpRoute
  ListVillaRoute: typeof ListVillaRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizersRoute: typeof OrganizersRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  VillasRoute: typeof VillasRouteWithChildren
  BookingVillaRoute: typeof BookingVillaRouteWithChildren
  CheckoutEventRoute: typeof CheckoutEventRouteWithChildren
  DashboardOrganizerRoute: typeof DashboardOrganizerRouteWithChildren
  DashboardVillaOwnerRoute: typeof DashboardVillaOwnerRouteWithChildren
  HostIdRoute: typeof HostIdRoute
  OrganizerIdRoute: typeof OrganizerIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-villa': {
      id: '/list-villa'
      path: '/list-villa'
      fullPath: '/list-villa'
      preLoaderRoute: typeof ListVillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-organizer': {
      id: '/become-organizer'
      path: '/become-organizer'
      fullPath: '/become-organizer'
      preLoaderRoute: typeof BecomeOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$id': {
      id: '/villas/$id'
      path: '/$id'
      fullPath: '/villas/$id'
      preLoaderRoute: typeof VillasIdRouteImport
      parentRoute: typeof VillasRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$id': {
      id: '/organizer/$id'
      path: '/organizer/$id'
      fullPath: '/organizer/$id'
      preLoaderRoute: typeof OrganizerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$id': {
      id: '/host/$id'
      path: '/host/$id'
      fullPath: '/host/$id'
      preLoaderRoute: typeof HostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id': {
      id: '/experiences/$id'
      path: '/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof ExperiencesIdRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/villa-owner': {
      id: '/dashboard/villa-owner'
      path: '/dashboard/villa-owner'
      fullPath: '/dashboard/villa-owner'
      preLoaderRoute: typeof DashboardVillaOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organizer': {
      id: '/dashboard/organizer'
      path: '/dashboard/organizer'
      fullPath: '/dashboard/organizer'
      preLoaderRoute: typeof DashboardOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/event': {
      id: '/checkout/event'
      path: '/checkout/event'
      fullPath: '/checkout/event'
      preLoaderRoute: typeof CheckoutEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/villa': {
      id: '/booking/villa'
      path: '/booking/villa'
      fullPath: '/booking/villa'
      preLoaderRoute: typeof BookingVillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/villas': {
      id: '/admin/villas'
      path: '/villas'
      fullPath: '/admin/villas'
      preLoaderRoute: typeof AdminVillasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/villa-owner/settings': {
      id: '/dashboard/villa-owner/settings'
      path: '/settings'
      fullPath: '/dashboard/villa-owner/settings'
      preLoaderRoute: typeof DashboardVillaOwnerSettingsRouteImport
      parentRoute: typeof DashboardVillaOwnerRoute
    }
    '/dashboard/villa-owner/properties': {
      id: '/dashboard/villa-owner/properties'
      path: '/properties'
      fullPath: '/dashboard/villa-owner/properties'
      preLoaderRoute: typeof DashboardVillaOwnerPropertiesRouteImport
      parentRoute: typeof DashboardVillaOwnerRoute
    }
    '/dashboard/villa-owner/earnings': {
      id: '/dashboard/villa-owner/earnings'
      path: '/earnings'
      fullPath: '/dashboard/villa-owner/earnings'
      preLoaderRoute: typeof DashboardVillaOwnerEarningsRouteImport
      parentRoute: typeof DashboardVillaOwnerRoute
    }
    '/dashboard/villa-owner/bookings': {
      id: '/dashboard/villa-owner/bookings'
      path: '/bookings'
      fullPath: '/dashboard/villa-owner/bookings'
      preLoaderRoute: typeof DashboardVillaOwnerBookingsRouteImport
      parentRoute: typeof DashboardVillaOwnerRoute
    }
    '/dashboard/organizer/tickets': {
      id: '/dashboard/organizer/tickets'
      path: '/tickets'
      fullPath: '/dashboard/organizer/tickets'
      preLoaderRoute: typeof DashboardOrganizerTicketsRouteImport
      parentRoute: typeof DashboardOrganizerRoute
    }
    '/dashboard/organizer/settings': {
      id: '/dashboard/organizer/settings'
      path: '/settings'
      fullPath: '/dashboard/organizer/settings'
      preLoaderRoute: typeof DashboardOrganizerSettingsRouteImport
      parentRoute: typeof DashboardOrganizerRoute
    }
    '/dashboard/organizer/events': {
      id: '/dashboard/organizer/events'
      path: '/events'
      fullPath: '/dashboard/organizer/events'
      preLoaderRoute: typeof DashboardOrganizerEventsRouteImport
      parentRoute: typeof DashboardOrganizerRoute
    }
    '/dashboard/organizer/attendees': {
      id: '/dashboard/organizer/attendees'
      path: '/attendees'
      fullPath: '/dashboard/organizer/attendees'
      preLoaderRoute: typeof DashboardOrganizerAttendeesRouteImport
      parentRoute: typeof DashboardOrganizerRoute
    }
    '/dashboard/organizer/analytics': {
      id: '/dashboard/organizer/analytics'
      path: '/analytics'
      fullPath: '/dashboard/organizer/analytics'
      preLoaderRoute: typeof DashboardOrganizerAnalyticsRouteImport
      parentRoute: typeof DashboardOrganizerRoute
    }
    '/checkout/event/success': {
      id: '/checkout/event/success'
      path: '/success'
      fullPath: '/checkout/event/success'
      preLoaderRoute: typeof CheckoutEventSuccessRouteImport
      parentRoute: typeof CheckoutEventRoute
    }
    '/booking/villa/success': {
      id: '/booking/villa/success'
      path: '/success'
      fullPath: '/booking/villa/success'
      preLoaderRoute: typeof BookingVillaSuccessRouteImport
      parentRoute: typeof BookingVillaRoute
    }
    '/dashboard/organizer/events/new': {
      id: '/dashboard/organizer/events/new'
      path: '/new'
      fullPath: '/dashboard/organizer/events/new'
      preLoaderRoute: typeof DashboardOrganizerEventsNewRouteImport
      parentRoute: typeof DashboardOrganizerEventsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVillasRoute: typeof AdminVillasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVillasRoute: AdminVillasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesIdRoute: typeof ExperiencesIdRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesIdRoute: ExperiencesIdRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface VillasRouteChildren {
  VillasIdRoute: typeof VillasIdRoute
}

const VillasRouteChildren: VillasRouteChildren = {
  VillasIdRoute: VillasIdRoute,
}

const VillasRouteWithChildren =
  VillasRoute._addFileChildren(VillasRouteChildren)

interface BookingVillaRouteChildren {
  BookingVillaSuccessRoute: typeof BookingVillaSuccessRoute
}

const BookingVillaRouteChildren: BookingVillaRouteChildren = {
  BookingVillaSuccessRoute: BookingVillaSuccessRoute,
}

const BookingVillaRouteWithChildren = BookingVillaRoute._addFileChildren(
  BookingVillaRouteChildren,
)

interface CheckoutEventRouteChildren {
  CheckoutEventSuccessRoute: typeof CheckoutEventSuccessRoute
}

const CheckoutEventRouteChildren: CheckoutEventRouteChildren = {
  CheckoutEventSuccessRoute: CheckoutEventSuccessRoute,
}

const CheckoutEventRouteWithChildren = CheckoutEventRoute._addFileChildren(
  CheckoutEventRouteChildren,
)

interface DashboardOrganizerEventsRouteChildren {
  DashboardOrganizerEventsNewRoute: typeof DashboardOrganizerEventsNewRoute
}

const DashboardOrganizerEventsRouteChildren: DashboardOrganizerEventsRouteChildren =
  {
    DashboardOrganizerEventsNewRoute: DashboardOrganizerEventsNewRoute,
  }

const DashboardOrganizerEventsRouteWithChildren =
  DashboardOrganizerEventsRoute._addFileChildren(
    DashboardOrganizerEventsRouteChildren,
  )

interface DashboardOrganizerRouteChildren {
  DashboardOrganizerAnalyticsRoute: typeof DashboardOrganizerAnalyticsRoute
  DashboardOrganizerAttendeesRoute: typeof DashboardOrganizerAttendeesRoute
  DashboardOrganizerEventsRoute: typeof DashboardOrganizerEventsRouteWithChildren
  DashboardOrganizerSettingsRoute: typeof DashboardOrganizerSettingsRoute
  DashboardOrganizerTicketsRoute: typeof DashboardOrganizerTicketsRoute
}

const DashboardOrganizerRouteChildren: DashboardOrganizerRouteChildren = {
  DashboardOrganizerAnalyticsRoute: DashboardOrganizerAnalyticsRoute,
  DashboardOrganizerAttendeesRoute: DashboardOrganizerAttendeesRoute,
  DashboardOrganizerEventsRoute: DashboardOrganizerEventsRouteWithChildren,
  DashboardOrganizerSettingsRoute: DashboardOrganizerSettingsRoute,
  DashboardOrganizerTicketsRoute: DashboardOrganizerTicketsRoute,
}

const DashboardOrganizerRouteWithChildren =
  DashboardOrganizerRoute._addFileChildren(DashboardOrganizerRouteChildren)

interface DashboardVillaOwnerRouteChildren {
  DashboardVillaOwnerBookingsRoute: typeof DashboardVillaOwnerBookingsRoute
  DashboardVillaOwnerEarningsRoute: typeof DashboardVillaOwnerEarningsRoute
  DashboardVillaOwnerPropertiesRoute: typeof DashboardVillaOwnerPropertiesRoute
  DashboardVillaOwnerSettingsRoute: typeof DashboardVillaOwnerSettingsRoute
}

const DashboardVillaOwnerRouteChildren: DashboardVillaOwnerRouteChildren = {
  DashboardVillaOwnerBookingsRoute: DashboardVillaOwnerBookingsRoute,
  DashboardVillaOwnerEarningsRoute: DashboardVillaOwnerEarningsRoute,
  DashboardVillaOwnerPropertiesRoute: DashboardVillaOwnerPropertiesRoute,
  DashboardVillaOwnerSettingsRoute: DashboardVillaOwnerSettingsRoute,
}

const DashboardVillaOwnerRouteWithChildren =
  DashboardVillaOwnerRoute._addFileChildren(DashboardVillaOwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeOrganizerRoute: BecomeOrganizerRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  FeedRoute: FeedRoute,
  HelpRoute: HelpRoute,
  ListVillaRoute: ListVillaRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizersRoute: OrganizersRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRouteWithChildren,
  VillasRoute: VillasRouteWithChildren,
  BookingVillaRoute: BookingVillaRouteWithChildren,
  CheckoutEventRoute: CheckoutEventRouteWithChildren,
  DashboardOrganizerRoute: DashboardOrganizerRouteWithChildren,
  DashboardVillaOwnerRoute: DashboardVillaOwnerRouteWithChildren,
  HostIdRoute: HostIdRoute,
  OrganizerIdRoute: OrganizerIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
